# Generated by Django 3.1.7 on 2021-03-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterCreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proficiencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='charClass',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spellSlots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='proficiencies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.proficiencies'),
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharacterCreator.spells'),
        ),
    ]
