# Generated by Django 3.1.7 on 2021-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterCreator', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='race',
            field=models.CharField(default='human', max_length=25),
            preserve_default=False,
        ),
    ]
