# Generated by Django 3.1.7 on 2021-03-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterCreator', '0005_auto_20210322_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ac',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='attackBonus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.CharField(default='EMPTY', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='proficiencies',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='spellSaveDC',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
