# Generated by Django 3.1.7 on 2021-03-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterCreator', '0010_auto_20210325_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Parties',
        ),
    ]
