# Generated by Django 3.1.7 on 2021-03-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterCreator', '0012_character_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spellName', models.CharField(max_length=100)),
                ('spellLevel', models.IntegerField()),
                ('spellDescription', models.CharField(max_length=1000)),
                ('spellDamage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('damageType', models.CharField(max_length=100)),
                ('savingThrow', models.CharField(max_length=25)),
                ('spellRange', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('castingTime', models.IntegerField()),
                ('ritual', models.BooleanField()),
                ('verbal', models.BooleanField()),
                ('somatic', models.BooleanField()),
                ('material', models.BooleanField()),
                ('bard', models.BooleanField()),
                ('cleric', models.BooleanField()),
                ('druid', models.BooleanField()),
                ('paladin', models.BooleanField()),
                ('ranger', models.BooleanField()),
                ('sorcerer', models.BooleanField()),
                ('warlock', models.BooleanField()),
                ('wizard', models.BooleanField()),
            ],
        ),
    ]
