# Generated by Django 3.1.7 on 2021-04-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterCreator', '0014_auto_20210331_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spells',
            old_name='spellDescription',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='spells',
            old_name='spellLevel',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='spells',
            old_name='spellName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='materialComponents',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='somatic',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='spellDamage',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='verbal',
        ),
        migrations.AddField(
            model_name='spells',
            name='attack_type',
            field=models.CharField(default='normal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spells',
            name='components',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spells',
            name='higher_level',
            field=models.CharField(default='does extra damage', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spells',
            name='index',
            field=models.CharField(default='index', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spells',
            name='castingTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spells',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spells',
            name='material',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='spells',
            name='spellRange',
            field=models.CharField(max_length=100),
        ),
    ]
