# Generated by Django 3.1.7 on 2021-04-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterCreator', '0015_auto_20210401_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spells',
            name='index',
        ),
    ]
