/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:230e8af3-9f00-480e-b2f1-a8aed4d407a3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_YyDWXdtNp",
    "aws_user_pools_web_client_id": "5mh823n91tm7tf9mul8t023gn8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fobvtyulhfa25admaceao2f3ue.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
